name: Build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        ls -Rl /home/runner/work/SimpleRT/SimpleRT/simple-rt-android
        cp /home/runner/work/SimpleRT/SimpleRT/simple-rt-android/app/build/outputs/apk/release/app-release-unsigned.apk /home/runner/work/SimpleRT/SimpleRT/SimpleRT.apk

    - name: Upload .apk
      uses: actions/upload-artifact@v1
      with:
        name: SimpleRT
        path: SimpleRT.apk
