name: Build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        ./simple-rt-android/gradlew assembleDebug
        ls -Rl /home/runner/work/SimpleRT|grep apk

- name: Upload apk
  uses: actions/upload-artifact@v2
  with:
    name: debug apk
    path: app/build/outputs/apk/debug/app-debug.apk
